language: node_js
sudo: false
node_js:
  - "5.7.0"
notifications:
  email:
    - yelm-eng@microsoft.com
addons:
  apt:
    packages:
      - libc6-i386

node_js:
  - "6"

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-9-2019-q4-major

install:
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-9-2019-q4-major
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

script:
    - make all-boards
